apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaduqfh2985-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaduqfh2985-tenant-component
    app.kubernetes.io/part-of: loaduqfh2985-tenant-app
  name: loaduqfh2985-tenant-component
  namespace: loaduqfh2985-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loaduqfh2985-tenant-component
    weight: null
status: {}
